project:
  type: website
  output-dir: _site
  preview:
    port: 4200
    browser: true

website:
  title: "My Blog"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/neeraja-sai-m-6a2711279
      - icon: github
        href: https://github.com/
format:
  html:
    theme: cosmo
    css: styles.css



